### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by hyZhang0701** [zhuyingda/yastjson#1]
Usage部分：
let jsonString = '{a:1}',应该写成：
let jsonString = '{"a":1}'

**Comment by zhuyingda** [comment]
收到，感谢反馈

**Comment by zhuyingda** [comment]
https://github.com/zhuyingda/yastjson/commit/824fa7f6616db113b3d6714b707736c9bfdfded0

**Comment by zhuyingda** [comment]
fixed and close.
